package unl.soc.producer_consumer;

import org.apache.logging.log4j.Level;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.core.config.Configurator;
import org.apache.logging.log4j.core.config.DefaultConfiguration;

public class Simulation {

	private static final Logger LOGGER = LogManager.getLogger(Simulation.class);

	public static final int NUM_REQUEST_GENERATORS = 3;
	public static final int NUM_REQUEST_HANDLERS = 3;
	
	/**
	 * Requests are configured to be randomly generated by each generator based
	 * on the following two parameters.  Each generator will generate one request
	 * randomly every 2-5 seconds.  
	 */
	public static final double REQUEST_GENERATION_INTERVAL_SEC_MIN = 2.0;
	public static final double REQUEST_GENERATION_INTERVAL_SEC_MAX = 5.0;

	public static void main(String args[]) {
		Configurator.initialize(new DefaultConfiguration());
		Configurator.setRootLevel(Level.INFO);
		LOGGER.info("Starting Simulation...");

		RequestManager.initialize();
	}

}
